version: "3.9"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000           # id -u
      - PGID=1000           # id -g
      - TZ=America/Denver
    volumes:
      - ./config/sabnzbd:/config
      - /mnt/downloads:/data/downloads
      - /mnt/media:/data/media
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks: [arrnet]

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./config/sonarr:/config
      - /mnt/media:/data/media
      - /mnt/downloads:/data/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks: [arrnet]

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./config/radarr:/config
      - /mnt/media:/data/media
      - /mnt/downloads:/data/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks: [arrnet]

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks: [arrnet]
    
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
    volumes:
      - ./config/lidarr:/config
      - /mnt/media:/data/media
      - /mnt/downloads:/data/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped
    networks: [arrnet]


networks:
  arrnet:
    name: arrnet
